pipeline {
    agent any
    
    environment {
            APP_NAME="Excel-2"
    }



    stages {
        stage('Checkout') {
            steps {
                echo "Clonando repo"
                checkout scm
            }
        }

        stage('Lint') {
            when {
                branch 'main'
                branch pattern: "feature/.*", comparator: "REGEXP"
            }
            steps {
                echo "sh npm instal"
                echo "sh npm run lint"
                echo "El package.son debe tener: 'scripts': {'lint': 'eslint'. }"
            }
        }

        stage('Backend Tests') {
            steps {
                echo "Aqui van los tests de Python"
            }
        }

        stage('Run Test Features') {
            when {
                branch pattern: "feature/.*", comparator: "REGEXP"        
            }
            steps {
                echo 'Esto es un feature'
            }
        }

        stage('PR') {
                changeRequest target: 'main'
            }
    }



    post {
        success {
            echo "Pipeline completado :)"
        }
        failure {
            echo "Pipeline fallo :("
        }
    }
}
