pipeline {
    agent any
    
    environment {
            APP_NAME="Excel-2"
            POSTGRES_USER = credentials('postgres-user')
            POSTGRES_PASSWORD = credentials('postgres-pass')
            POSTGRES_DB = excel_db 
    }



    stages {
        stage('Checkout') {
            steps {
                echo "Clonando repo"
                checkout scm
            }
        }

        

        stage ('Lint Backend') {
            agent {
                docker {
                    image 'python:3.11-slim'
                    args '-u root'
                }    
            }

            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    echo 'Executing flake8...'
                    script {
                        sh '''
                            python -m pip install --no-cache-dir flake8
                            flake8 backend --max-line-length=120
                            ls -la 
                        '''
                    }
                }
            }
        }


        stage ('Lint Frontend') {
            agent {
                docker {
                    image 'node:20-bullseye-slim'
                    }
                }
            steps {
                catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                    echo "Executing ESLint..."
                    script {
                        sh '''
                            cd frontend
                            npm install --silent 
                            npm run lint
                        '''
                    }
                }
            }
        }
        


        stage('Build Containers') {
            agent {
                docker {
                    image 'docker:cli'
                    args '-u root -v /var/run/docker.sock:/var/run/docker.sock -e HOME=/tmp'
                }
            }
            steps {
                sh '''
                    echo $POSTGRES_PASSWORD
                    echo $POSTGRES_USER
                    echo $POSTGRES_DB
                    pwd
                    docker compose -f docker/docker-compose.ci.yml build
                '''
            }
        }


        stage('Test Containers') {
            agent {
                docker {
                    image 'docker:cli'
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                sh 'docker compose -f docker/docker-compose.ci.yml up -d'
                sh 'sleep 10'
                sh 'docker compose -f docker/docker-compose.ci.yml ps'

                sh 'curl --fail http://localhost:8081/health || exit 1'
                //sh 'curl --fail http://localhost:3001 || exit 1'
                sh 'docker compose -f docker/docker-compose.ci.yml exec backend curl http://localhost:8080/health'
            }
        }



        // examples
        stage('Lint') {
            when {
                branch 'main'
                branch pattern: "feature/.*", comparator: "REGEXP"
            }
            steps {
                echo "sh npm instal"
                echo "sh npm run lint"
                echo "El package.son debe tener: 'scripts': {'lint': 'eslint'. }"
            }
        }

        stage('Backend Tests') {
            steps {
                echo "Aqui van los tests de Python"
            }
        }

        stage('Run Test Features') {
            when {
                branch pattern: "feature/.*", comparator: "REGEXP"        
            }
            steps {
                echo 'Esto es un feature'
            }
        }

        stage('PR') {
            when { 
                changeRequest target: 'main' 
            }
            steps {
                echo "Validaciones extra para pull requests"
            }
        }
    }



    post {
        always {
            sh 'docker compose -f docker/docker-compose.ci.yml down -v'
        }
        
        success {
            echo "Pipeline completado :)"
        }
        
        failure {
            echo "Pipeline fallo :("
        }
    }
}
