"""Add user_category_preferences table

Revision ID: 10d5c046334c
Revises: e385e80b37f5
Create Date: 2026-07-05 17:55:10.833077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10d5c046334c'
down_revision: Union[str, Sequence[str], None] = 'e385e80b37f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hidden_categories_id'), table_name='hidden_categories')
    op.drop_table('hidden_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hidden_categories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('hidden_categories_category_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('hidden_categories_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hidden_categories_pkey'))
    )
    op.create_index(op.f('ix_hidden_categories_id'), 'hidden_categories', ['id'], unique=False)
    # ### end Alembic commands ###
