"""Fix models imports, and fix passwords/tokens

Revision ID: 218c00c1b5b5
Revises: c0c7e2a1816c
Create Date: 2026-07-12 04:06:23.636651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218c00c1b5b5'
down_revision: Union[str, Sequence[str], None] = 'c0c7e2a1816c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
