"""Fix preferences

Revision ID: c0c7e2a1816c
Revises: 10d5c046334c
Create Date: 2026-07-05 21:11:09.850572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c7e2a1816c'
down_revision: Union[str, Sequence[str], None] = '10d5c046334c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_hidden')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_hidden', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
