"""Add is_hidden to categories and fix wrong field

Revision ID: e385e80b37f5
Revises: 43fb62b9e001
Create Date: 2026-07-05 07:18:09.930712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e385e80b37f5'
down_revision: Union[str, Sequence[str], None] = '43fb62b9e001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_hidden')
    # ### end Alembic commands ###
